binding/ruby/ext/core/rb-milter-socket-address.c

```log
rb-milter-socket-address.c: In function 'unix_pack':
rb-milter-socket-address.c:171:21: warning: comparison between signed
and unsigned integer expressions [-Wsign-compare]
if (path_length > sizeof(address.sun_path))
^
```
path_length seems to be always greater than or equals 0.

binding ruby: Suppress -Wsign-compare warning

---

test/core/test-connection.c

Because simply using "localhost" in parse_connection_spec_inet6 test
causes following error:
```log
Failure: test_parse_connection_spec_inet6 (full - host name)
expected: <error> is NULL
actual: <milter-connection-error-quark:0: invalid host address:
<inet6:9999@localhost>: <localhost>: <名前またはサービスが不明です>>
/home/hhatake/Github/milter-manager/test/core/test-connection.c:402:
test_parse_connection_spec_inet6(): gcut_assert_error(error, )
```
And /etc/hosts says IPv6 version of "localhost" nodename is:
```bash
% cat /etc/hosts
...
::1     ip6-localhost ip6-loopback
...
```
But I do not have enough confidence that this fix is correct....

core test: Try to use "ip6-localhost" in parse_connection_spec_inet6 test

---

doc/install-to-ubuntu.rd
doc/install-to-ubuntu.rd.ja
doc/upgrade-on-ubuntu.rd
doc/upgrade-on-ubuntu.rd.ja

Milter-manager already didn't support this version of Ubuntu.

doc: Remove installation manual for Ubuntu Saucy (13.10)

---

binding/ruby/Makefile.am

Because following error occurred while rpm building:
```log
configure: checking bundled Ruby/GLib2 2.2.5
/usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- pkg-config (LoadError)
from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from /home/milter-manager-build/rpm/BUILD/milter-manager-2.0.5/binding/ruby/glib-2.2.5/lib/mkmf-gnome2.rb:14:in `<top (required)>'
from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from /home/milter-manager-build/rpm/BUILD/milter-manager-2.0.5/binding/ruby/glib-2.2.5/ext/glib2/extconf.rb:15:in `<main>'
configure: error: Ruby/GLib2 is required.
error: Bad exit status from …
```

binding ruby: Add missing pkg-config.rb

---

package/rpm/centos/milter-manager.spec.in
package/yum/build-rpm.sh
package/yum/vendor/ruby22.spec

In my chrooted CentOS 6 environment, creating Ruby 2.2.3 rpms and installing these rpms works fine.

package yum rpm: Bundle Ruby 2.2.3 in CentOS6

---

doc/milter-test-client.rd

```log
BACKEDN ->
BACKEND
^^
```

doc: fix a typo

---

doc/release.rd.ja

`rbenv` does not create `ruby.so` by default.

doc: Add note for using rbenv

---

configure.ac
data/Makefile.am
data/systemd/Makefile.am
data/systemd/redhat/Makefile.am
data/systemd/redhat/milter-manager.service
package/rpm/centos/milter-manager.spec.in

I've tried to add systemd unit file for CentOS7.
This unit file works like this:
```log
$ sudo systemctl start milter-manager
$ sudo systemctl status milter-manager -l
milter-manager.service - milter-manager server daemon
Loaded: loaded (/usr/lib/systemd/system/milter-manager.service; disabled)
Active: active (running) since 火 2015-11-24 06:54:12 GMT; 6s ago
Main PID: 4254 (milter-manager)
CGroup: /system.slice/milter-manager.service
├─4254 /usr/sbin/milter-manager --pid-file /var/run/milter-manager/milter-manager.pid
└─4258 /usr/sbin/milter-manager --pid-file /var/run/milter-manager/milter-manager.pid
11月 24 06:54:12 localhost.localdomain systemd[1]: Started milter-manager server daemon.
```
This implementation is early stage. So, perhaps, it's not sophisticated about packaging, systemd …

redhat systemd: Add systemd unit file for CentOS7

---

binding/ruby/lib/milter/client/session-context.rb

'falback-status' option is not working when 'temporary-failure'.
milter program abend in the confirmation of TEMPORARY-FAILURE(Milter::STATUS)
i think 'TEMPORARY_FAILURE' is correct. please fix.
$ ruby -r milter -e 'p Milter::VERSION'
[2, 0, 7]

Error "in `const_get': wrong constant name TEMPORARY-FAILURE" occurs

---

package/yum/build-release-rpm.sh

```
Loaded plugins: fastestmirror
http://downloads.sourceforge.net/project/milter-manager/centos/7/stable/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
To address this issue please refer to the below knowledge base article 
https://access.redhat.com/articles/1320623
If above article doesn't help to resolve this issue please create a bug on https://bugs.centos.org/
One of the configured repositories failed (milter manager for CentOS 7 - x86_64),
and yum doesn't have enough cached data to continue. At this point the only
safe thing yum can do is fail. There are a few ways to work "fix" this:
1. Contact the upstream for the repository and get them to fix the problem.
2. Reconfigure the baseurl/etc. for the repository, to point to a working
upstream. …
```

CentOS 7: installation failed due to repodata/repomd.xml HTTP Error 404

---

milter/server/milter-server-context.c
milter/server/milter-server-context.h
tool/milter-test-server.c

1. 以下の4つのタイムアウト値を一括で変更するオプション(--all-timeout)を追加しました。
- connection\-timeout
- reading\-timeout
- writing\-timeout
- end\-of\-message\-timeout
2. milter-test-server --helpにall-timeoutオプションの説明と使い方を追加しました。
all-timeoutオプションに0以上の値を設定することで本機能は有効になります。
all-timeoutオプションを指定しない または、負の値を設定した場合は、本機能は無効になります。

milter-test-server: add disable timeout option

---

data/applicable-conditions/dnsbl.conf

Implemented a DNSBL based applicable condition.
milter-manager uses S25R as an applicable condition of milter-greylist by default. S25R is mostly sound but not complete, and actually many spammers evade application of milter-greylist.
DNSBL could be an another choice for an applicable condition of milter-greylist.
Current implementation uses SPAMHAUS, SORBS, SPAMCOP, BARRACUDA as default black hole lists.
DNS resolvers are multithreaded for each black hole list, so adding more black hole lists does not increase processing latency.

add DNSBL applicable condition

---

Makefile.am

It is better to provide the way to verify release archive.

Add cryptographic signature for integrity

---

binding/ruby/test/manager/test-freebsd-rc-detector.rb

Because root user can read all files.

test: Omit `test_rc_script_readable?`

---

doc/configuration.rd
doc/configuration.rd.ja

ドキュメントの内容が以前の「Authentication」になっていたので「Authenticated」に修正

Fix "Authentication" typos in configuration document

---

milter/core/milter-utils.c

This commit fixes the following random error:
(It was caused because GHashTable doesn't gurantee the order of inserted
keys)
Failure: test_inspect_hash_string_string
<"{" "\"name1\" => \"value1\", " "\"name2\" => \"value2\"" "}" ==
inspected>
expected: <"{\"name1\" => \"value1\", \"name2\" => \"value2\"}">
actual: <"{\"name2\" => \"value2\", \"name1\" => \"value1\"}">

milter core: ensure to sort hash table keys

---

doc/available-milters.rd
doc/available-milters.rd.ja

moved 5 years ago and old URL is owned by someone else now.

doc available-milters: update milter-regex URL

---

binding/ruby/ext/core/rb-milter-decoder.c
binding/ruby/ext/manager/rb-milter-manager-control-decoder.c

G_DEF_ERROR2 requires GQuark, but MILTER_TYPE_* returns GType

Fix confusion between GQuark and GType

---

.github/workflows/package.yml
Vagrantfile
package/apt/test.sh
package/debian/rules
package/yum/test.sh

Package tests are failing now: https://github.com/milter-manager/milter-manager/actions/runs/2701480108
We have to use vagrant to use `systemd` for these tests.
However, we can't use vagrant on Ubuntu in the CI-environment.
So this fix uses macOS for tests.
I refer Mroonga.
* https://github.com/mroonga/mroonga
* https://github.com/mroonga/mroonga/blob/master/.github/workflows/linux.yml
* https://github.com/mroonga/mroonga/blob/master/Vagrantfile
TODO

ci: fix package tests failing

---

meson-config.h.in
meson.build
milter/client/meson.build
milter/core/meson.build

This fix tries to build milter-client with Meson as well as https://github.com/milter-manager/milter-manager/pull/159.
Currently I get the following error: `error: ‘GETTEXT_PACKAGE’ undeclared`
```console
$ meson setup --prefix=/tmp/local ../milter-manager.build .
$ ninja -C ../milter-manager.build
(omit)
[1/4] Compiling C object 'milter/client/2b66477@@milter-client@sha/milter-client-main.c.o'.
FAILED: milter/client/2b66477@@milter-client@sha/milter-client-main.c.o 
cc -Imilter/client/2b66477@@milter-client@sha -Imilter/client -I../milter-manager/milter/client -I. -I../milter-manager/ -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -g -fPIC -DEV_COMPAT3=0 -DHAVE_CONFIG_H …
```

Support Meson for milter-client

---

milter/client/meson.build
milter/core/meson.build

The Meson version is wrongly used now.
We have to use the project version here.

Fix to use the project version instead of meson version

---

milter/client/meson.build
milter/core/meson.build

We must use `meson.project_version()` here,
but we can omit the `version` option to use the project version.
https://mesonbuild.com/Pkgconfig-module.html#pkggenerate

Use the project version for pkgconfig instead of meson version

---

meson.build
milter/client/meson.build
milter/core/meson.build
milter/server/meson.build

Add `milter-manager` to the path: `${PREFIX}/include/milter-manager`.
For example, use `${PREFIX}/include/milter-manager/milter/client` for `milter/client`'s install_dir.

Fix install_dir for Meson

---

meson.build

It seems that we need a backslash for a new line, like Python.
I have confirmed the backslash resolves this error.
```console
$ meson setup --prefix=/tmp/local -Dpackage_platform=debian ../milter-manager.build .
$ ninja -C ../milter-manager.build
...
meson.build:81:4: ERROR: Unknown statement.
```

meson: need backslash for new line

---

meson.build

This fix is for Meson 0.53.2 of Ubuntu focal.
`dependency()`:
* I got the error: `meson.build:179:0: ERROR: Expected 1 arguments, got 5.`
* More than one name can be provided since 0.60.0
* https://mesonbuild.com/Reference-manual_functions.html#dependency
`dep.get_variable()`:
* I got the error: `meson.build:183:2: ERROR: Function does not take positional arguments.`
* `varname` is since 0.58.0
* https://mesonbuild.com/Reference-manual_returned_dep.html#depget_variable

meson: support Ubuntu focal again

---

binding/python/gi/overrides/MilterCore/logger.py

The signature of `traceback.print_exception` changed at Python 3.10:
* https://docs.python.org/ja/3/library/traceback.html#traceback.print_exception
* https://docs.python.org/ja/3.8/library/traceback.html#traceback.print_exception
For example, the following code is valid for Python 3.10, but invalid for Python 3.8.
```py
import traceback
import io
e = Exception("hoge")
output = io.StringIO()
traceback.print_exception(e, file=output)
message = output.getvalue()
message
```
This causes the following error with Python 3.8.10:
```
1 output = io.StringIO()
----> 2 traceback.print_exception(e,file=output)
3 message = output.getvalue()
4 message
TypeError: print_exception() missing 2 required positional arguments: 'value' and 'tb'
```
This is also a problem when using fallback_status.
According …

python logger: support Python 3.8

---

binding/python/sample/milter-external.py
binding/python/sample/milter-replace.py

I found some needless codes.
In addition, I refactored some code shapes.
https://peps.python.org/pep-0008/#programming-recommendations
(`is not`  is mentioned, but there doesn't seem to be any specific mention of `A not in B`...
However, I often see `A not in B` than `not A in B`)

python: simplify milter samples

---

binding/ruby/lib/milter/client.rb

body-bytes was disabled by not setting set_use_bytes(true) in client.rb.
I also had to replace end_of_message with end_of_message_bytes.
<pre>
/**
* milter_client_context_set_use_bytes:
* @context: A #MilterClientContext.
* @use: Whether #MilterClientContext::body-bytes and
*   #MilterClientContext::end-of-message-bytes are used instead of
*   #MilterClientContext::body and
*   #MilterClientContext::end-of-message.
*
* Since: 2.1.6
*/
</pre>

set use_bytes on ruby milter client

---

.github/workflows/test.yml
compose.yaml

Docker Compose v1 is not supported on GitHub runners:
https://github.blog/changelog/2024-04-10-github-hosted-runner-images-deprecation-notice-docker-compose-v1/

ci test: use Docker Compose v2

---

.github/workflows/package.yml

The paths of these repo were wrong since eb62d47542f8c150b1d83ba1cf39c87e2d34aaa2.
They should be absolute because of `cd` before the `rake version:update`.
The error occurs in:
cd package
rake version:update RELEASE_DATE=$(date +%Y-%m-%d)
The content of the error:
rake aborted!
LoadError: cannot load such file -- groonga/packages/packages-groonga-org-package-task
<internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:86:in `require'
<internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:86:in `require'
/home/runner/work/milter-manager/milter-manager/package/Rakefile:21:in `<top (required)>'

ci package: fix build error

---

compose.yaml
dockerfiles/debian-bookworm.dockerfile

In 37785834dc36de0372cd03378d495683293d4352, the setting for `compose.yaml` was missing.

ci test: fix failing Debian Bookworm tests
